name: API Typescript Build
on: [push]
jobs:
  tsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20.9.0
          cache: 'yarn'
          cache-dependency-path: 'server/yarn.lock'
      - run: cd server/ && yarn
      - run: cd server/ && yarn run tsc
